const { syncWholegoodsToEquipment } = require('../../src/utils/match_wholegoods_with_equipment');

describe('syncWholegoodsToEquipment', () => {
	it('updates 3 equipment and creates 2 new equipment using sample data', async () => {
		const equipmentList = [
			{ equipmentId: 14064074, rimssId: 5907 },
			{ equipmentId: 8088955, rimssId: 5913 },
			{ equipmentId: 8088956, rimssId: 5905 },
		];

		const wholegoods = [
			{
				systemID: 5905,
				inactive: false,
				stockNumber: '2019-5905',
				company: 'MADSEN CONSTRUCTION EQUIPMENT',
				locationId: 3,
				owningLocation: 'CASE ATLANTIC',
				location: 'Customer',
				make: 'Case',
				model: '48035240',
				description: 'Case 36" High Flow SV280 Cold Planer',
				serialNumber: '48035240',
				type: 'Sales',
				salesStatus: 'Sold',
				taxStatus: 'Taxable',
				fleetNumber: '',
				newUsed: 'New',
				category: 'Attachments',
				group: '',
				class: '',
				miles: 0,
				hours: 0,
				orderDate: '9999-12-31T23:59:59.9999999',
				arrivalDate: '9999-12-31T23:59:59.9999999',
				inServiceDate: '9999-12-31T23:59:59.9999999',
				soldDate: '2019-08-01T00:00:00',
				dueDate: '9999-12-31T23:59:59.9999999',
				owningCustomer: 'Case Atlantic - Sales Department (245)',
				billingCustomer: 'Case Atlantic - Sales Department (245)',
				engine: '',
				cylinders: '',
				horsePower: '',
				displacement: '',
				fuelDelivery: '',
				compressionRatio: '',
				torque: '',
				fuelType: '',
				transmission: '',
				gearRatio: '',
				driveType: '',
				rearPTORPM: '',
				rearPTOHP: '',
				midPTORPM: '',
				midPTOHP: '',
				numberOfRemotes: '',
				length: '',
				width: '',
				height: '',
				dryWeight: '',
				wetWeight: '',
				wheelBase: '',
				rops: '',
				hitchCategory: '',
				hitchLiftCapacity: '',
				hitchLiftCapacityAt24: '',
				frontTires: '',
				rearTires: '',
				brakes: '',
				wgUserDefinedField1: 'SOLD',
				wgUserDefinedField2: 'THis WG was originally ordered through parts on RO 406913',
				wgUserDefinedField3: '',
				wgUserDefinedField4: 'Infinity Construction',
				wgUserDefinedField5: '2019-0052',
				wgUserDefinedField6: '',
				wgUserDefinedField7: '2019-5674-0L',
				wgUserDefinedField8: '',
				wgUserDefinedField9: '',
				wgUserDefinedField10: '',
				wgUserDefinedField11: '',
				wgUserDefinedField12: '',
				wgUserDefinedField13: '0.0000',
				wgUserDefinedField14: '0.0000',
				wgUserDefinedField15: '0.0000',
				wholegoodCustomField1: '',
				wholegoodCustomField2: '',
				wholegoodCustomField3: '',
				wholegoodCustomField4: '',
				wholegoodCustomField5: '',
				wholegoodCustomField6: '',
				wholegoodCustomField7: '',
				wholegoodCustomField8: '',
				wholegoodCustomField9: '',
				wholegoodCustomField10: '',
				wholegoodCustomField11: '',
				wholegoodCustomField12: '',
				wholegoodCustomField13: '',
				wholegoodCustomField14: '',
				wholegoodCustomField15: '',
				wholegoodCustomField16: '',
				wholegoodCustomField17: '',
				wholegoodCustomField18: '',
				wholegoodCustomField19: '',
				wholegoodCustomField20: '',
				costTotal: 0,
				liabilityAmount: 0,
				msrp: 0,
				askingPrice: 0,
				mfgCost: 0,
				estimatedPDI: 0,
				minSellingPrice: 0,
				inventoryAccount: 'CAS-1-12240-01',
				liabilityAccount: '',
				revenueAccount: 'CAS-4-40240-04',
				cogsAccount: 'CAS-5-60240-04',
				onOrder: false,
				year: '',
				createdDate: '2019-08-06T08:55:00',
				updatedDate: '2019-08-06T08:54:36.637',
				costDetailDocuments: [],
				liabilityDetailDocuments: [],
				workInProcessDetailDocuments: [],
			},
			{
				systemID: 5907,
				inactive: false,
				stockNumber: '2019-5907',
				company: 'MADSEN CONSTRUCTION EQUIPMENT',
				locationId: 3,
				owningLocation: 'CASE ATLANTIC',
				location: 'Customer',
				make: 'AMI Attachments',
				model: 'Ditch Cleaning Bucket',
				description: 'AMI 36" Ditching Bucket',
				serialNumber: '195479-01-01',
				type: 'Sales',
				salesStatus: 'Sold',
				taxStatus: 'Taxable',
				fleetNumber: '',
				newUsed: 'New',
				category: 'Attachments',
				group: '',
				class: '',
				miles: 0,
				hours: 0,
				orderDate: '2019-08-08T00:00:00',
				arrivalDate: '2019-09-17T00:00:00',
				inServiceDate: '9999-12-31T23:59:59.9999999',
				soldDate: '2020-07-16T00:00:00',
				dueDate: '9999-12-31T23:59:59.9999999',
				owningCustomer: 'Dober Enterprises (8223)',
				billingCustomer: 'Dober Enterprises (8223)',
				engine: '',
				cylinders: '',
				horsePower: '',
				displacement: '',
				fuelDelivery: '',
				compressionRatio: '',
				torque: '',
				fuelType: '',
				transmission: '',
				gearRatio: '',
				driveType: '',
				rearPTORPM: '',
				rearPTOHP: '',
				midPTORPM: '',
				midPTOHP: '',
				numberOfRemotes: '',
				length: '',
				width: '',
				height: '',
				dryWeight: '',
				wetWeight: '',
				wheelBase: '',
				rops: '',
				hitchCategory: '',
				hitchLiftCapacity: '',
				hitchLiftCapacityAt24: '',
				frontTires: '',
				rearTires: '',
				brakes: '',
				wgUserDefinedField1: 'SOLD',
				wgUserDefinedField2: 'Ordered as per WC email for Jody Collier CX37C',
				wgUserDefinedField3: '',
				wgUserDefinedField4: 'Dober Enterprises',
				wgUserDefinedField5: '2018-0021',
				wgUserDefinedField6: '',
				wgUserDefinedField7: '2017-5061-0L',
				wgUserDefinedField8: '',
				wgUserDefinedField9: '',
				wgUserDefinedField10: '',
				wgUserDefinedField11: '',
				wgUserDefinedField12: '',
				wgUserDefinedField13: '0.0000',
				wgUserDefinedField14: '0.0000',
				wgUserDefinedField15: '0.0000',
				wholegoodCustomField1: '',
				wholegoodCustomField2: '',
				wholegoodCustomField3: '',
				wholegoodCustomField4: '',
				wholegoodCustomField5: '',
				wholegoodCustomField6: '',
				wholegoodCustomField7: '',
				wholegoodCustomField8: '',
				wholegoodCustomField9: '',
				wholegoodCustomField10: '',
				wholegoodCustomField11: '',
				wholegoodCustomField12: '',
				wholegoodCustomField13: '',
				wholegoodCustomField14: '',
				wholegoodCustomField15: '',
				wholegoodCustomField16: '',
				wholegoodCustomField17: '',
				wholegoodCustomField18: '',
				wholegoodCustomField19: '',
				wholegoodCustomField20: '',
				costTotal: 0,
				liabilityAmount: 0,
				msrp: 0,
				askingPrice: 0,
				mfgCost: 0,
				estimatedPDI: 0,
				minSellingPrice: 0,
				inventoryAccount: 'CAS-1-12240-01',
				liabilityAccount: '',
				revenueAccount: 'CAS-4-40240-04',
				cogsAccount: 'CAS-5-60240-04',
				onOrder: false,
				year: '',
				createdDate: '2019-08-08T14:42:00',
				updatedDate: '2020-08-04T07:50:07.733',
				costDetailDocuments: [ {}, {}, {} ],
				liabilityDetailDocuments: [],
				workInProcessDetailDocuments: [],
			},
			{
				systemID: 5911,
				inactive: false,
				stockNumber: '2019-5911',
				company: 'MADSEN CONSTRUCTION EQUIPMENT',
				locationId: 3,
				owningLocation: 'CASE ATLANTIC',
				location: 'Customer',
				make: 'Case',
				model: '87441572',
				description: 'Case 93" Backhoe Bucket',
				serialNumber: '2019-5911',
				type: 'Sales',
				salesStatus: 'Sold',
				taxStatus: 'Taxable',
				fleetNumber: '',
				newUsed: 'New',
				category: 'Attachments',
				group: '',
				class: '',
				miles: 0,
				hours: 739,
				orderDate: '2019-08-15T00:00:00',
				arrivalDate: '2019-09-18T00:00:00',
				inServiceDate: '9999-12-31T23:59:59.9999999',
				soldDate: '2020-06-29T00:00:00',
				dueDate: '9999-12-31T23:59:59.9999999',
				owningCustomer: 'Dominion Paving 2010 Limited (293)',
				billingCustomer: 'Dominion Paving 2010 Limited (293)',
				engine: '',
				cylinders: '',
				horsePower: '',
				displacement: '',
				fuelDelivery: '',
				compressionRatio: '',
				torque: '',
				fuelType: '',
				transmission: '',
				gearRatio: '',
				driveType: '',
				rearPTORPM: '',
				rearPTOHP: '',
				midPTORPM: '',
				midPTOHP: '',
				numberOfRemotes: '',
				length: '',
				width: '',
				height: '',
				dryWeight: '',
				wetWeight: '',
				wheelBase: '',
				rops: '',
				hitchCategory: '',
				hitchLiftCapacity: '',
				hitchLiftCapacityAt24: '',
				frontTires: '',
				rearTires: '',
				brakes: '',
				wgUserDefinedField1: 'SOLD',
				wgUserDefinedField2: '',
				wgUserDefinedField3: '',
				wgUserDefinedField4: 'Dominion Paving',
				wgUserDefinedField5: '2020-0105',
				wgUserDefinedField6: '',
				wgUserDefinedField7: '2019-6004-0L',
				wgUserDefinedField8: '',
				wgUserDefinedField9: '',
				wgUserDefinedField10: '',
				wgUserDefinedField11: '',
				wgUserDefinedField12: '',
				wgUserDefinedField13: '0.0000',
				wgUserDefinedField14: '0.0000',
				wgUserDefinedField15: '0.0000',
				wholegoodCustomField1: '',
				wholegoodCustomField2: '',
				wholegoodCustomField3: '',
				wholegoodCustomField4: '',
				wholegoodCustomField5: '',
				wholegoodCustomField6: '',
				wholegoodCustomField7: '',
				wholegoodCustomField8: '',
				wholegoodCustomField9: '',
				wholegoodCustomField10: '',
				wholegoodCustomField11: '',
				wholegoodCustomField12: '',
				wholegoodCustomField13: '',
				wholegoodCustomField14: '',
				wholegoodCustomField15: '',
				wholegoodCustomField16: '',
				wholegoodCustomField17: '',
				wholegoodCustomField18: '',
				wholegoodCustomField19: '',
				wholegoodCustomField20: '',
				costTotal: 0,
				liabilityAmount: 0,
				msrp: 0,
				askingPrice: 0,
				mfgCost: 0,
				estimatedPDI: 0,
				minSellingPrice: 0,
				inventoryAccount: 'CAS-1-12240-01',
				liabilityAccount: '',
				revenueAccount: 'CAS-4-40240-04',
				cogsAccount: 'CAS-5-60240-04',
				onOrder: false,
				year: '',
				createdDate: '2019-08-15T08:00:00',
				updatedDate: '2020-07-03T08:53:55.22',
				costDetailDocuments: [ {}, {} ],
				liabilityDetailDocuments: [],
				workInProcessDetailDocuments: [],
			},
			{
				systemID: 5912,
				inactive: false,
				stockNumber: '2019-5912',
				company: 'MADSEN CONSTRUCTION EQUIPMENT',
				locationId: 3,
				owningLocation: 'CASE ATLANTIC',
				location: 'Customer',
				make: 'Case',
				model: '87441572',
				description: 'Case 93" Backhoe Bucket',
				serialNumber: '2019-5912, 1312540002520',
				type: 'Sales',
				salesStatus: 'Sold',
				taxStatus: 'Taxable',
				fleetNumber: '',
				newUsed: 'New',
				category: 'Attachments',
				group: '',
				class: '',
				miles: 0,
				hours: 0,
				orderDate: '2019-08-15T00:00:00',
				arrivalDate: '2019-09-18T00:00:00',
				inServiceDate: '9999-12-31T23:59:59.9999999',
				soldDate: '2022-12-29T00:00:00',
				dueDate: '9999-12-31T23:59:59.9999999',
				owningCustomer: "SAN / LOR Fishery's Ltd (11858)",
				billingCustomer: "SAN / LOR Fishery's Ltd (11858)",
				engine: '',
				cylinders: '',
				horsePower: '',
				displacement: '',
				fuelDelivery: '',
				compressionRatio: '',
				torque: '',
				fuelType: '',
				transmission: '',
				gearRatio: '',
				driveType: '',
				rearPTORPM: '',
				rearPTOHP: '',
				midPTORPM: '',
				midPTOHP: '',
				numberOfRemotes: '',
				length: '',
				width: '',
				height: '',
				dryWeight: '',
				wetWeight: '',
				wheelBase: '',
				rops: '',
				hitchCategory: '',
				hitchLiftCapacity: '',
				hitchLiftCapacityAt24: '',
				frontTires: '',
				rearTires: '',
				brakes: '',
				wgUserDefinedField1: 'SOLD',
				wgUserDefinedField2: '',
				wgUserDefinedField3: '',
				wgUserDefinedField4: 'San/Lor',
				wgUserDefinedField5: '2021-0092',
				wgUserDefinedField6: '',
				wgUserDefinedField7: '*2020-6360-0L ?, See Note - formerly 2019-6077-0L',
				wgUserDefinedField8: '',
				wgUserDefinedField9: '',
				wgUserDefinedField10: '',
				wgUserDefinedField11: '',
				wgUserDefinedField12: '',
				wgUserDefinedField13: '0.0000',
				wgUserDefinedField14: '0.0000',
				wgUserDefinedField15: '0.0000',
				wholegoodCustomField1: '',
				wholegoodCustomField2: '',
				wholegoodCustomField3: '',
				wholegoodCustomField4: '',
				wholegoodCustomField5: '',
				wholegoodCustomField6: '',
				wholegoodCustomField7: '',
				wholegoodCustomField8: '',
				wholegoodCustomField9: '',
				wholegoodCustomField10: '',
				wholegoodCustomField11: '',
				wholegoodCustomField12: '',
				wholegoodCustomField13: '',
				wholegoodCustomField14: '',
				wholegoodCustomField15: '',
				wholegoodCustomField16: '',
				wholegoodCustomField17: '',
				wholegoodCustomField18: '',
				wholegoodCustomField19: '',
				wholegoodCustomField20: '',
				costTotal: 0,
				liabilityAmount: 0,
				msrp: 0,
				askingPrice: 0,
				mfgCost: 0,
				estimatedPDI: 0,
				minSellingPrice: 0,
				inventoryAccount: 'CAS-1-12240-01',
				liabilityAccount: '',
				revenueAccount: 'CAS-4-40240-04',
				cogsAccount: 'CAS-5-60240-04',
				onOrder: false,
				year: '',
				createdDate: '2019-08-15T08:01:00',
				updatedDate: '2022-06-08T15:42:21.617',
				costDetailDocuments: [ {}, {} ],
				liabilityDetailDocuments: [],
				workInProcessDetailDocuments: [],
			},
			{
				systemID: 5913,
				inactive: false,
				stockNumber: '2019-5913',
				company: 'MADSEN CONSTRUCTION EQUIPMENT',
				locationId: 3,
				owningLocation: 'CASE ATLANTIC',
				location: 'Yard',
				make: 'Case',
				model: '87441572',
				description: 'Case 93" Backhoe Bucket',
				serialNumber: '2019-5913',
				type: 'Sales',
				salesStatus: 'AFS',
				taxStatus: 'Taxable',
				fleetNumber: '',
				newUsed: 'New',
				category: 'Attachments',
				group: '',
				class: '',
				miles: 0,
				hours: 0,
				orderDate: '2019-08-15T00:00:00',
				arrivalDate: '2019-09-18T00:00:00',
				inServiceDate: '9999-12-31T23:59:59.9999999',
				soldDate: '9999-12-31T23:59:59.9999999',
				dueDate: '9999-12-31T23:59:59.9999999',
				owningCustomer: '',
				billingCustomer: '',
				engine: '',
				cylinders: '',
				horsePower: '',
				displacement: '',
				fuelDelivery: '',
				compressionRatio: '',
				torque: '',
				fuelType: '',
				transmission: '',
				gearRatio: '',
				driveType: '',
				rearPTORPM: '',
				rearPTOHP: '',
				midPTORPM: '',
				midPTOHP: '',
				numberOfRemotes: '',
				length: '',
				width: '',
				height: '',
				dryWeight: '',
				wetWeight: '',
				wheelBase: '',
				rops: '',
				hitchCategory: '',
				hitchLiftCapacity: '',
				hitchLiftCapacityAt24: '',
				frontTires: '',
				rearTires: '',
				brakes: '',
				wgUserDefinedField1: 'STK-N',
				wgUserDefinedField2: '',
				wgUserDefinedField3: '',
				wgUserDefinedField4: 'Case Atlantic',
				wgUserDefinedField5: '',
				wgUserDefinedField6: '',
				wgUserDefinedField7: '',
				wgUserDefinedField8: '',
				wgUserDefinedField9: '',
				wgUserDefinedField10: '',
				wgUserDefinedField11: '',
				wgUserDefinedField12: '',
				wgUserDefinedField13: '0.0000',
				wgUserDefinedField14: '0.0000',
				wgUserDefinedField15: '0.0000',
				wholegoodCustomField1: '',
				wholegoodCustomField2: '',
				wholegoodCustomField3: '',
				wholegoodCustomField4: '',
				wholegoodCustomField5: '',
				wholegoodCustomField6: '',
				wholegoodCustomField7: '',
				wholegoodCustomField8: '',
				wholegoodCustomField9: '',
				wholegoodCustomField10: '',
				wholegoodCustomField11: '',
				wholegoodCustomField12: '',
				wholegoodCustomField13: '',
				wholegoodCustomField14: '',
				wholegoodCustomField15: '',
				wholegoodCustomField16: '',
				wholegoodCustomField17: '',
				wholegoodCustomField18: '',
				wholegoodCustomField19: '',
				wholegoodCustomField20: '',
				costTotal: 2768.76,
				liabilityAmount: 0,
				msrp: 0,
				askingPrice: 0,
				mfgCost: 0,
				estimatedPDI: 0,
				minSellingPrice: 0,
				inventoryAccount: 'CAS-1-12240-01',
				liabilityAccount: '',
				revenueAccount: 'CAS-4-40240-04',
				cogsAccount: 'CAS-5-60240-04',
				onOrder: false,
				year: '',
				createdDate: '2019-08-15T08:02:00',
				updatedDate: '2020-04-23T14:48:30.12',
				costDetailDocuments: [ {} ],
				liabilityDetailDocuments: [],
				workInProcessDetailDocuments: [],
			},
		];

		const updateEquipment = jest.fn(async () => undefined);
		const createEquipment = jest.fn(async () => undefined);

		const results = await syncWholegoodsToEquipment({
			wholegoods,
			equipmentList: equipmentList.slice(),
			updateEquipment,
			createEquipment,
		});

		expect(updateEquipment).toHaveBeenCalledTimes(3);
		expect(createEquipment).toHaveBeenCalledTimes(2);
		expect(results.updated).toBe(3);
		expect(results.created).toBe(2);
		expect(results.remainingEquipment).toHaveLength(0);

		const updatedSystemIds = updateEquipment.mock.calls
			.map(([wholegood]) => wholegood.systemID)
			.sort((a, b) => a - b);
		const createdSystemIds = createEquipment.mock.calls
			.map(([wholegood]) => wholegood.systemID)
			.sort((a, b) => a - b);

		expect(updatedSystemIds).toEqual([5905, 5907, 5913]);
		expect(createdSystemIds).toEqual([5911, 5912]);
	});
});
